# This is the default configuration file. Enabling and disabling is configured
# in separate files. This file adds all other parameters apart from Enabled.

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - Gemfile
    - bin/*
    - config/initializers/*_bootstrap.rb
Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Max: 150

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 160

IndentationWidth:
  Enabled: true

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - redis

